joinedRoom = false;
roomname = "";
rooms = [];
buffer_seek(oClient.clientBuffer, buffer_seek_start, 0);
buffer_write(oClient.clientBuffer, buffer_u8, Network.ListRooms);
network_send_packet(oClient.client, oClient.clientBuffer, buffer_tell(oClient.clientBuffer));
selectedroom = 0;
sprites=0;
ishost = 0;
players = "";